# production database configuration
development:
  adapter: mysql
  encoding: utf8
  database: ranmoshe_yaroki
  pool: 5
  username: ranmoshe_rani
  password: yeledy@r0k

test:
  adapter: mysql
  encoding: utf8
  database: ranmoshe_yaroki
  pool: 5
  username: ranmoshe_rani
  password: yeledy@r0k

production:
  adapter: mysql
  encoding: utf8
  database: ranmoshe_yaroki
  pool: 5
  username: ranmoshe_rani
  password: yeledy@r0k
