# Default database configuration

development:
  adapter: mysql
  encoding: utf8
  database: yaroki_development
  pool: 5
  username: root
  password: ranmoshe
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  adapter: sqlite3
  database: db/production.sqlite3
                                    
# special mode for demo.spreecommerce.com (you probably don't need this)                                    
demo:
  adapter: sqlite3
  database: db/production.sqlite3
